import type { Metadata } from "next";

/**
 * Canonical site origin used for absolute URLs in metadata, OpenGraph,
 * sitemap and JSON-LD. Set NEXT_PUBLIC_SITE_URL in production (e.g.
 * https://prompthub.com); falls back to localhost for local dev.
 */
export const SITE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3002"
).replace(/\/$/, "");

export const SITE_NAME = "PromptVault";

export const SITE_DESCRIPTION =
  "A free, ad-supported library of 1,000+ AI prompt packs for ChatGPT, Claude, Gemini and Midjourney. Browse by category, copy any prompt — no account, no paywall.";

/** Default social share image (1200×630), generated by the /og route. */
export const DEFAULT_OG_IMAGE = `${SITE_URL}/og`;

export function absoluteUrl(path = "/"): string {
  if (/^https?:\/\//i.test(path)) return path;
  return `${SITE_URL}${path.startsWith("/") ? "" : "/"}${path}`;
}

/** Truncate to a clean meta-description length (~155 chars) on a word boundary. */
export function clampDescription(text: string | null | undefined, max = 155): string {
  const t = (text || "").replace(/\s+/g, " ").trim();
  if (t.length <= max) return t;
  return `${t.slice(0, max - 1).replace(/\s+\S*$/, "")}…`;
}

/**
 * Build a consistent Metadata object for a page: title, description,
 * canonical, OpenGraph and Twitter card. `path` should be the canonical route.
 */
export function buildMetadata(input: {
  title: string;
  description?: string | null;
  path: string;
  image?: string | null;
  type?: "website" | "article";
  noIndex?: boolean;
  publishedTime?: string | null;
}): Metadata {
  const description = clampDescription(input.description) || SITE_DESCRIPTION;
  const url = absoluteUrl(input.path);
  const image = input.image || DEFAULT_OG_IMAGE;

  return {
    title: input.title,
    description,
    alternates: { canonical: url },
    robots: input.noIndex
      ? { index: false, follow: false }
      : { index: true, follow: true },
    openGraph: {
      title: input.title,
      description,
      url,
      siteName: SITE_NAME,
      type: input.type || "website",
      images: [{ url: image, width: 1200, height: 630, alt: input.title }],
      ...(input.publishedTime
        ? { publishedTime: input.publishedTime }
        : {}),
    },
    twitter: {
      card: "summary_large_image",
      title: input.title,
      description,
      images: [image],
    },
  };
}
