import type { Metadata } from "next";
import meta from "@/data/meta.json";

/**
 * Canonical site origin used for absolute URLs in metadata, OpenGraph,
 * sitemap, robots and JSON-LD.
 *
 * Set NEXT_PUBLIC_SITE_URL to your real domain in production (e.g.
 * https://yourdomain.com). Until it is set, a documented placeholder is used so
 * builds succeed — but canonical URLs, the sitemap and social previews will be
 * wrong until you point it at the live domain.
 */
export const SITE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL || "https://aiprompts.example"
).replace(/\/$/, "");

/** True when a real production domain has been configured. */
export const SITE_URL_IS_PLACEHOLDER =
  !process.env.NEXT_PUBLIC_SITE_URL ||
  /localhost|127\.0\.0\.1|\.example$/.test(SITE_URL);

export const SITE_NAME = "PromptVault";

/** Live catalog totals — kept accurate automatically from the built dataset. */
export const PACK_COUNT = meta.packCount;
export const PROMPT_COUNT = meta.promptCount;

const nf = new Intl.NumberFormat("en-US");
export const PACK_COUNT_FMT = nf.format(PACK_COUNT);
export const PROMPT_COUNT_FMT = nf.format(PROMPT_COUNT);

export const SITE_TAGLINE = `${PACK_COUNT_FMT}+ Free AI Prompt Packs for ChatGPT, Claude, Gemini & Midjourney`;

export const SITE_DESCRIPTION =
  `A free, ad-supported library of ${PACK_COUNT_FMT} AI prompt packs ` +
  `(${PROMPT_COUNT_FMT} ready-to-use prompts) for ChatGPT, Claude, Gemini and ` +
  `Midjourney. Browse by category and copy any prompt — no account, no paywall.`;

export function absoluteUrl(path = "/"): string {
  if (/^https?:\/\//i.test(path)) return path;
  return `${SITE_URL}${path.startsWith("/") ? "" : "/"}${path}`;
}

/**
 * Build a URL to the dynamic OpenGraph image (1200×630) rendered by /og.
 * Passing a title/eyebrow yields a page-specific social card; with no args it
 * returns the default branded image.
 */
export function ogImageUrl(input?: {
  title?: string;
  eyebrow?: string;
  note?: string;
}): string {
  if (!input || (!input.title && !input.eyebrow && !input.note)) {
    return `${SITE_URL}/og`;
  }
  const params = new URLSearchParams();
  if (input.title) params.set("title", input.title);
  if (input.eyebrow) params.set("eyebrow", input.eyebrow);
  if (input.note) params.set("note", input.note);
  return `${SITE_URL}/og?${params.toString()}`;
}

/** Default social share image (1200×630), generated by the /og route. */
export const DEFAULT_OG_IMAGE = ogImageUrl();

/** schema.org BreadcrumbList from an ordered list of {name, path}. */
export function breadcrumbLd(items: { name: string; path: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((it, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: it.name,
      item: absoluteUrl(it.path),
    })),
  };
}

/** schema.org ItemList linking to a set of pack pages. */
export function itemListLd(
  name: string,
  items: { id: string; title: string }[],
) {
  return {
    "@context": "https://schema.org",
    "@type": "ItemList",
    name,
    numberOfItems: items.length,
    itemListElement: items.map((it, i) => ({
      "@type": "ListItem",
      position: i + 1,
      url: absoluteUrl(`/packs/${it.id}`),
      name: it.title,
    })),
  };
}

/** schema.org FAQPage from Q/A pairs — eligible for rich results & AI answers. */
export function faqLd(qa: { q: string; a: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: qa.map(({ q, a }) => ({
      "@type": "Question",
      name: q,
      acceptedAnswer: { "@type": "Answer", text: a },
    })),
  };
}

/** Truncate to a clean meta-description length (~155 chars) on a word boundary. */
export function clampDescription(text: string | null | undefined, max = 155): string {
  const t = (text || "").replace(/\s+/g, " ").trim();
  if (t.length <= max) return t;
  return `${t.slice(0, max - 1).replace(/\s+\S*$/, "")}…`;
}

/**
 * Build a consistent Metadata object for a page: title, description,
 * canonical, OpenGraph and Twitter card. `path` should be the canonical route.
 */
export function buildMetadata(input: {
  title: string;
  description?: string | null;
  path: string;
  image?: string | null;
  type?: "website" | "article";
  noIndex?: boolean;
  publishedTime?: string | null;
}): Metadata {
  const description = clampDescription(input.description) || SITE_DESCRIPTION;
  const url = absoluteUrl(input.path);
  const image = input.image || DEFAULT_OG_IMAGE;

  return {
    title: input.title,
    description,
    alternates: { canonical: url },
    robots: input.noIndex
      ? { index: false, follow: false }
      : {
          index: true,
          follow: true,
          googleBot: {
            index: true,
            follow: true,
            "max-image-preview": "large",
            "max-snippet": -1,
            "max-video-preview": -1,
          },
        },
    openGraph: {
      title: input.title,
      description,
      url,
      siteName: SITE_NAME,
      locale: "en_US",
      type: input.type || "website",
      images: [{ url: image, width: 1200, height: 630, alt: input.title }],
      ...(input.publishedTime ? { publishedTime: input.publishedTime } : {}),
    },
    twitter: {
      card: "summary_large_image",
      title: input.title,
      description,
      images: [image],
    },
  };
}
